spring:
  application:
    name: windfarm-server
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:windfarm}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 16
      connection-timeout: 30000
  jackson:
    time-zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    com.greenko.windfarm: INFO

windfarm:
  dataset-path: ${DATASET_PATH:data/device_energy_data.csv}
  emitter:
    enabled: true
    interval: PT0.5S
    accelerated-interval: PT0.1S
    accelerate: ${EMIT_ACCELERATE:true}
  listener:
    enabled: true
    flush-interval: PT0.2S
    batch-size: 500
  seed:
    enabled: ${WINDFARM_SEED_ENABLED:false}
    minutes: ${WINDFARM_SEED_MINUTES:180}
